@extends ('menu')

@section ('title', 'Termos de uso : EstBank')

@section ('conteudo')

<div class="container"></div>
<section class="section-scroll section-one">
    <div class="container">
        <div class="row">
            <div class="col-12 px-3">
                <h3 class="bradcrumb c-gray-blue mt-5 pt-4"></h3>
                <div class="d-flex align-items-center justify-content-center">
                    <h1 class="subtitle-small c-pink mb-0 text-uppercase">Termos de uso</h1>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12 col-sm-10 offset-sm-1 px-5 c-gray-blue text-scroll-small">
                <p><strong>DATA DE ÚLTIMA ATUALIZAÇÃO:</strong> 14 / 02 / 2022.</p>
<p><strong>INTRODUÇÃO: QUAL A FINALIDADE DESTES TERMOS DE USO?</strong></p>
<p>Estes termos e condições gerais de uso (“<span style="text-decoration: underline;">Termos de Uso</span>”), juntamente com a Política de Privacidade (“<span style="text-decoration: underline;">Política de Privacidade</span>”), descrevem os direitos e obrigações dos usuários (“<span style="text-decoration: underline;">Você</span>” ou “<span style="text-decoration: underline;">Titular</span>”) ao adquirirem e utilizarem os serviços aqui descritos (“<span style="text-decoration: underline;">Serviços</span>”).</p>
<p><strong>AO UTILIZAR OS SERVIÇOS OFERECIDOS, VOCÊ AUTOMATICAMENTE CONCORDA COM TODAS AS REGRAS DESTES TERMOS DE USO E DEMAIS CONDIÇÕES AQUI MENCIONADAS, RESPONSABILIZANDO-SE INTEGRALMENTE POR TODOS E QUAISQUER ATOS PRATICADOS AO UTILIZAR NOSSOS SERVIÇOS. CASO VOCÊ NÃO CONCORDE COM QUALQUER DOS TERMOS E CONDIÇÕES ABAIXO ESTABELECIDOS, VOCÊ NÃO DEVE UTILIZAR OS SERVIÇOS.</strong></p>
<p>Os Serviços são oferecidos pela EST Gestão de Bens S/A, sociedade limitada de capital fechado com sede na cidade de São Paulo, estado de São Paulo, na Avenida Nove de Julho, no 3147, CJ 111/112, Jardim Paulista, CEP 4107000, inscrita no CNPJ sob o no 37.920.778/0001-29, em parceria com a IDEZ Administração de Meios de Pagamento Digital Ltda., sociedade limitada com sede na cidade de Porto Alegre, Estado do Rio Grande do Sul, na Rua Henrique Dias, 220, sala 9, Bom Fim, CEP 90.035-100, inscrita no CNPJ sob o no 33.652.365/0001-50.</p>
<p><strong>1. QUAIS SÃO AS DEFINIÇÕES IMPORTANTES DESTES TERMOS DE USO?</strong></p>
<p><strong>1.1.</strong> Sem prejuízo de outras definições atribuídas nestes Termos de Uso, as palavras abaixo, quando utilizadas no singular ou plural, terão os seguintes significados:</p>
<p>(i) <strong>Aplicações:</strong> são aplicações de internet como, por exemplo, site ou aplicativo mobile, disponibilizados para que Você possa gerenciar sua Conta, na forma prevista nestes Termos de Uso.</p>
<p>(ii) <strong>Bandeira:</strong> é a VISA, instituidora dos arranjos de pagamento VISA, empresa responsável pela marca e pelos sistemas físicos e digitais que permitem a emissão do Cartão e sua utilização nos Estabelecimentos, de acordo com a Lei no 12.865/2013 e com o Regulamento dos Arranjos de Pagamento da VISA, disponível no site da VISA.</p>
<p>(iii) <strong>Canais de Comunicação:</strong> são os canais oficiais para comunicação entre Você e a EST Gestão de Bens S/A, para assuntos relacionados ao uso dos Serviços aqui descritos, sendo que qualquer outro canal de comunicação que não esteja descrito aqui, ou nas Aplicações, não é considerado um canal oficial, e Você não deve utilizá-lo. Os Canais de Comunicação são os seguintes:</p>
<p>a. <strong>Chat Online.</strong> Plataforma de suporte Zendesk;<br />
b. <strong>E-mail.</strong> O e-mail oficial para contato é operadores@estbank.com.br;<br />
c. <strong>Telefone.</strong> 11 3050.4030.</p>
<p>(iv) <strong>Cartão:</strong> é um cartão físico e/ou virtual que, a critério da EST Gestão de Bens S/A, pode ser oferecido a Você para usufruir os Serviços.</p>
<p>(v) <strong>Chargeback:</strong> é o procedimento de contestação de débito por meio do qual Você declara não reconhecer uma despesa efetuada com seu Cartão. Uma vez aceito o Chargeback, será realizado um depósito na Conta do Titular, no prazo informado pelos Canais de Comunicação.</p>
<p>(vi) <strong>Chave Pix:</strong> é a informação indicada pelo Titular para identificar sua Conta no âmbito do Pix e que pode consistir em um número de CPF ou CNPJ, número de seu telefone celular, endereço de e-mail e/ou uma chave aleatória, de livre escolha do Titular da Conta. O Titular poderá cadastrar até 5 (cinco) Chaves Pix para sua Conta. A(s) Chave(s) Pix permite(m) que uma das partes envolvidas em uma transação de pagamento obtenha as informações da outra parte armazenadas no Diretório de Identificadores de Contas Transacionais (DICT), gerido pelo Banco Central do Brasil, e que realize transações de pagamento no âmbito do Pix.</p>
<p>(vii) <strong>Conta:</strong> é a conta de pagamento pré-paga do Titular, gerida pela Instituição de Pagamento e destinada à execução de transações de pagamento em moeda eletrônica, realizadas com base em fundos denominados em reais, previamente aportados.</p>
<p>(viii) <strong>Estabelecimento:</strong> qualquer fornecedor de produtos e/ou serviços que está habilitado a aceitar pagamentos com o seu Cartão, no Brasil e/ou no exterior, em lojas físicas ou por meio da internet.</p>
<p>(ix) <strong>Instituição Financeira:</strong> é BV FINANCEIRA, instituição financeira responsável pelos serviços de individualização de contas de pagamento junto ao SPB (Sistema de Pagamento Brasileiro), que integrará sua relação com a EST Gestão de Bens S/A e a Parceira, sempre que Você tiver um número de banco, agência e conta atrelado aos Serviços.</p>
<p>(x) <strong>Instituição de Pagamento:</strong> é a DOCK SOLUÇÕES EM MEIOS DE PAGAMENTO S.A., sociedade anônima de capital fechado com sede na cidade de Barueri, estado de São Paulo, na Avenida Tamboré, no 267, Torre Norte, Edifício Canopus Corporate Alphaville, 10o andar, conjunto 101-B, Alphaville, CEP 06460-000, inscrita no CNPJ sob o no 08.744.817/0001-86, que, nos termos do artigo 6o, inciso III, da Lei no 12.865/2013, atua na qualidade de instituição de pagamento parceira de negócios da Parceira, sendo responsável pela abertura e gestão das Contas e pela emissão dos Cartões, razão pela qual dispõe de prerrogativas legais para atuar em relação à utilização das Contas e dos Cartões pelo Titular, sobretudo no que se refere à possibilidade de bloqueio preventivo e cancelamento de Contas e/ou Cartões, e de transações realizadas por meio das Contas;</p>
<p>(xi) <strong>Política de Privacidade:</strong> é o instrumento contratual que regula a coleta, uso, armazenamento, tratamento e segurança das informações pessoais dos Titulares, e que pode ser acessada aqui: <a href="https://estbank.com.br/politica-de-privacidade/">https://estbank.com.br/politica-de-privacidade/</a>. A Política de Privacidade é <span style="text-decoration: underline;">parte integrante e inseparável</span> destes Termos de Uso.</p>
<p>(xii) <strong>Você ou Titular:</strong> Pessoa Natural ou Jurídica, titular da Conta, que utiliza os Serviços.</p>
<p><strong>2. QUAIS SÃO OS SERVIÇOS OFERECIDOS?</strong></p>
<p><strong>2.1.</strong> A EST Gestão de Bens S/A, a Parceira e a Instituição de Pagamento oferecem a Você diversos serviços que possibilitam a movimentação de recursos financeiros e a realização de transações de pagamento. Para isso, Você deverá se cadastrar em algumas das aplicações de internet como, por exemplo, site (URL) ou aplicativo ESTBANK da EST Gestão de Bens S/A, ou diretamente nos pontos de vendas (indicados em [inserir URL]) da EST Gestão de Bens S/A.</p>
<p><strong>2.2.</strong> Uma vez realizado o cadastro, Você terá acesso a uma Conta e ao correspondente Cartão, para movimentação da Conta. O prazo para envio e recebimento deste Cartão será oportunamente informado pela EST Gestão de Bens S/A, e o acompanhamento da entrega poderá ser feito por meio dos Canais de Comunicação.</p>
<p><strong>2.3.</strong> Você declara ter ciência de que a Conta, a critério da EST Gestão de Bens S/A, poderá ser rentabilizada de acordo com o saldo nela disponível, sem qualquer ônus ao Titular, que, por este Termo, aceita receber tais eventuais rendimentos, que estão sujeitos à incidência de impostos.</p>
<p><strong>3. COMO EU ME CADASTRO PARA ACESSAR OS SERVIÇOS?</strong></p>
<p><strong>3.1.</strong> Para utilizar os Serviços, Você deve cadastrar-se por meio das Aplicações.</p>
<p><strong>3.2.</strong> O acesso aos Serviços é direcionado apenas às pessoas naturais maiores de 18 (dezoito) anos, residentes e domiciliadas no Brasil, que possuam plena capacidade legal e, para pessoas jurídicas, quando devidamente inscritas junto aos órgãos de registro e representadas nos termos do respectivo contrato ou estatuto social. Os Serviços serão usados exclusivamente pela pessoa do Titular ou, no caso das Contas mantidas por pessoas jurídicas, o uso se limitará à(s) pessoa(s) autorizada(s) a movimentar a Conta em nome do Titular.</p>
<p><strong>3.3.</strong> Para efetuar o cadastro, Você deve preencher certas informações pessoais, em observância ao art. 4o da Circular 3680/2013 do Banco Central do Brasil e/ou alterações posteriores, como por exemplo: nome completo ou denominação social, data de nascimento ou de constituição, número de inscrição no Cadastro de Pessoa Física (CPF) ou no Cadastro Nacional de Pessoas Jurídicas (CNPJ), endereço residencial ou da sede e número de telefone com DDD, bem como outras informações que podem ser exigidas pela EST Gestão de Bens S/A ou pela Instituição de Pagamento, como e-mail, nome de usuário (login) e senha (“<span style="text-decoration: underline;">Informações Pessoais</span>”). Você declara que as Informações Pessoais fornecidas voluntariamente no momento do cadastro são corretas, completas e verdadeiras, e <span style="text-decoration: underline;">compromete-se a sempre manter as Informações Pessoais atualizadas nas Aplicações</span>, responsabilizando-se por qualquer resultado ou prejuízo decorrente da falsidade das suas Informações Pessoais ou da não atualização delas.</p>
<p>A EST Gestão de Bens S/A, a Parceira, a Instituição de Pagamento e a Instituição Financeira em hipótese alguma serão responsáveis pela veracidade das Informações Pessoais fornecidas pelo Titular. Caso detectem a abertura de Conta a partir de informações falsas, incompletas, equivocadas, errôneas, enganosas, ou, que não permitam identificar a identidade do Titular, ou, ainda, caso detectem movimentações da Conta que apresentem possíveis indícios de fraude ou de operações que possam estar configuradas na Lei 9.613/98 (que dispõe sobre os crimes de lavagem ou ocultação de bens, direitos e valores), a EST Gestão de Bens S/A ou a Instituição de Pagamento poderão (i) solicitar esclarecimentos e documentação adicional que julgarem necessários para a devida comprovação das informações prestadas, para a validação do cadastro ou para as movimentações realizadas por meio da Conta, podendo, inclusive, recusarem-se a validar qualquer cadastro, a seu exclusivo critério ou (ii) automaticamente excluir o seu cadastro, suspender ou cancelar a sua permissão de utilizar os Serviços, caso os esclarecimentos ou informações solicitados não sejam encaminhadas pelo Titular, à respectiva solicitante, no prazo definido pela solicitante. Em caso de cancelamento da Conta, Você declara ter ciência de que o saldo disponível somente poderá ser transferido para conta de depósito ou de pagamento de sua titularidade.</p>
<p><strong>3.4.</strong> Todas as Informações Pessoais fornecidas voluntariamente por Você no momento do cadastro estão sujeitas às medidas de segurança que as protejam do acesso, do uso e da divulgação não autorizados. Para saber mais sobre a forma como a EST Gestão de Bens S/A coleta, compartilha e processa suas Informações Pessoais, por favor, acesse a Política de Privacidade da EST Gestão de Bens S/A no seguinte endereço: [URL].</p>
<p><strong>3.5.</strong> Uma vez que o cadastro tenha sido realizado e aprovado, Você passará a ter acesso à Conta, unicamente, por meio das Aplicações, mediante a utilização do login e senha criados no momento do cadastro. Você é o único responsável por sua Conta e por qualquer atividade associada a esta Conta. Neste sentido, é proibido o compartilhamento, pelo Titular, de seu login e senha com terceiros, devendo comunicar imediatamente à EST Gestão de Bens S/A no caso de perda, extravio ou furto de seu Cartão, login e/ou senha.</p>
<p>VOCÊ É O ÚNICO E EXCLUSIVO RESPONSÁVEL POR ACESSOS OU MOVIMENTAÇÕES EM SUA CONTA E/OU PELO USO INDEVIDO DE SEU CARTÃO POR TERCEIROS, BEM COMO POR QUALQUER DANO DIRETO OU INDIRETO QUE RESULTE DO MAU USO OU DA INABILIDADE DO USO DAS APLICAÇÕES, DA CONTA OU DO CARTÃO POR VOCÊ OU POR QUAISQUER TERCEIROS, SENDO CERTO QUE, HAVENDO EVIDÊNCIAS OU, AINDA, MEROS INDÍCIOS DE USO IRREGULAR, INADEQUADO, OU SUSPEITO DO CARTÃO E/OU DA CONTA, VOCÊ PODERÁ TER SEU CADASTRO IMEDIATAMENTE SUSPENSO OU, AINDA, CANCELADO, SEM PREJUÍZO DAS DEMAIS SANÇÕES LEGAIS E CONTRATUAIS.</p>
<p><strong>4. QUAIS SERVIÇOS SÃO OFERECIDOS POR MEIO DA CONTA?</strong></p>
<p><strong>4.1.</strong> Entre as principais operações que Você pode realizar por meio da Conta, sempre sujeitas à disponibilidade de saldo e sujeito à cobrança de taxas e tributos específicos, que serão descontados do saldo disponível na Conta, destacamos os seguintes “<span style="text-decoration: underline;">Serviços</span>”:</p>
<p>(i) <strong>Compras em Estabelecimentos:</strong> Você poderá realizar compras em qualquer fornecedor de produtos e/ou serviços que estejam habilitados a aceitar pagamentos com o seu Cartão, no Brasil e/ou no Exterior, em lojas físicas ou por meio da internet;</p>
<p>(ii) <strong>Emissão de Boletos:</strong> emissão de boletos, com o fim de transferir recursos para a sua Conta.</p>
<p>(iii) <strong>Pagamento de Boletos e Contas de Consumo:</strong> Você poderá realizar pagamentos de boletos e contas de consumo, sempre sujeito às limitações impostas pela legislação brasileira e pelas empresas emissoras dos respectivos títulos/boletos;</p>
<p>(iv) <strong>Pix:</strong> Se Você assim desejar, poderá realizar pagamentos e transferências a partir da solução de pagamento instantâneo criada e gerida pelo Banco Central do Brasil, disponível a partir do dia 16 de novembro de 2020, 24 (vinte e quatro) horas por dia, 7 (sete) dias por semana e em todos os dias do ano (incluindo sábados, domingos e feriados), que permite que os recursos relacionados a transações de pagamento estejam disponíveis em poucos segundos em sua Conta ou na conta do destinatário, após a realização da respectiva ordem de transferência, ressalvadas as hipóteses previstas no item 4.4.14;</p>
<p>(v) <strong>Recarga de Celular:</strong> Você poderá realizar pagamentos para a recarga de celular das operadoras cadastradas, sujeito às regras específicas de cada operadora;</p>
<p>(vi) <strong>Saque:</strong> Você poderá retirar da sua Conta recursos em terminais eletrônicos habilitados, mediante uso do Cartão. Nesta hipótese, poderão ser cobradas taxas pelas empresas administradoras desses terminais;</p>
<p>(vii) <strong>Transferências entre contas:</strong> Você poderá transferir recursos financeiros da sua Conta para contas de terceiros, bem como para contas de sua titularidade. A transferência entre contas também deverá observar os prazos e procedimentos previstos pelas normas que regem o sistema financeiro brasileiro;</p>
<p><strong>4.2.</strong> A Instituição de Pagamento reserva-se o direito de limitar a disponibilização de determinadas operações ao Titular, conforme os termos e condições acordados entre a EST Gestão de Bens S/A, a Parceira e a Instituição de Pagamento.</p>
<p><strong>4.3.</strong> Para ativar o uso de sua Conta, Você deve fazer aporte de um valor em reais, por meio das seguintes alternativas:</p>
<p>(i) <strong>Transferência Bancária:</strong> transferências bancárias efetuadas pelos aplicativos dos bancos, pelo internet banking e/ou caixas eletrônicos; e</p>
<p>(ii) <strong>Emissão de Boletos:</strong> emissão e pagamento de boletos, a serem pagos unicamente por Você, com o fim de transferir recursos para a sua Conta.</p>
<p>CADA OPERAÇÃO AQUI DESCRITA PODE TER LIMITAÇÕES TÉCNICAS E ESPECIFICAÇÕES DEFINIDAS PELA EST Gestão de Bens S/A OU PELA INSTITUIÇÃO DE PAGAMENTO, BEM COMO UMA REMUNERAÇÃO ESPECÍFICA, DE ACORDO COM O SERVIÇO REALIZADO, QUE SERÁ COBRADA MEDIANTE DÉBITO EM CONTA. O VALOR DE CADA TARIFA, OBSERVADA A REGULAMENTAÇÃO APLICÁVEL A CADA OPERAÇÃO, ESTÁ DISPONÍVEL NAS APLICAÇÕES.<br />
A EST Gestão de Bens S/A SE RESERVA O DIREITO DE ALTERAR AS TARIFAS A QUALQUER MOMENTO, SEMPRE INFORMANDO PREVIAMENTE O TITULAR, DE ACORDO COM A REGULAMENTAÇÃO APLICÁVEL, SENDO FACULTADO AO TITULAR CONCORDAR COM TAL ALTERAÇÃO OU CANCELAR SEU CADASTRO.</p>
<p><strong>4.4.</strong> Pix</p>
<p><strong>4.4.1.</strong> A EST Gestão de Bens S/A, a seu exclusivo critério, pode vir a ofertar os serviços de Pix. A transação realizada por meio do Pix poderá ser iniciada em sua Conta mediante (i) inserção manual dos dados da conta destinatária; (ii) inserção de uma Chave Pix da conta destinatária; ou (iii) geração (em caso de recebimento) ou leitura (em caso de pagamento ou transferência) de um Código QR.</p>
<p><strong>4.4.2.</strong> Havendo a oferta de Pix pela EST Gestão de Bens S/A, a qualquer momento, a seu exclusivo critério, Você poderá solicitar o registro de uma Chave Pix vinculada à sua Conta, sendo necessário que Você tenha a posse da Chave Pix escolhida (com exceção da chave aleatória) e que dê o seu consentimento para tal registro.</p>
<p><strong>4.4.3.</strong> Ao registrar uma Chave Pix, Você declara ter conhecimento de que os terceiros com quem Você realizar transações de pagamento por meio do Pix terão visibilidade, a cada transação, do seu nome completo, do seu CPF – com máscara escondendo os primeiros três e os últimos dois dígitos – e do nome da Instituição de Pagamento.</p>
<p><strong>4.4.4.</strong> Após o registro de qualquer Chave Pix vinculada à Conta, Você poderá, a qualquer momento, solicitar a portabilidade da Chave Pix (com exceção da chave aleatória), com o fim de transferir a vinculação de respectiva Chave Pix para outra conta de sua titularidade.</p>
<p><strong>4.4.5.</strong> Você poderá, ainda, receber a reivindicação de posse das Chaves Pix de número de telefone celular e/ou de endereço de e-mail, para transferir a vinculação de referida Chave Pix de uma conta de titularidade diferente para a sua Conta, ou de sua Conta para qualquer conta de titularidade diferente.</p>
<p><strong>4.4.6.</strong> A Chave Pix poderá ser excluída a qualquer momento do DICT, a pedido do Titular, ou diretamente pela Instituição de Pagamento, sem a necessidade de anuência do Titular, nos seguintes casos:</p>
<p>(i) inabilitação ou cancelamento da Conta;<br />
(ii) suspeita, tentativa ou efetivo uso fraudulento da Chave Pix; ou<br />
(iii) inatividade de uso da Chave Pix por mais de 12 (doze) meses consecutivos.</p>
<p><strong>4.4.7.</strong> O registro, a exclusão, a alteração, a portabilidade e a reivindicação de posse estarão disponíveis ao Titular 24 (vinte e quatro) horas por dia, 7 (sete) dias por semana, a partir do dia 16 de novembro de 2020.</p>
<p><strong>4.4.8.</strong> A realização, pelo Titular, de pré-cadastro para registro de sua Chave Pix implica na manifestação prévia de sua vontade e consentimento para o registro das Chaves Pix indicadas para vinculação à sua Conta. Tal manifestação será confirmada e o registro da Chave Pix será efetivado no DICT caso Você não exclua sua Chave Pix nas Aplicações.</p>
<p><strong>4.4.9.</strong> <strong>Uso da marca Pix.</strong> A marca Pix é de titularidade exclusiva do Banco Central do Brasil, que confere aos participantes do Pix, dentre eles, a Instituição de Pagamento, uma licença temporária, não exclusiva e intransferível de uso da marca, em suas formas nominativa e de símbolo, nos termos do art. 139 da Lei no 9.279, de 14 de maio de 1996.</p>
<p><strong>4.4.10.</strong> Todo e qualquer uso da marca Pix deverá estar em conformidade com os termos do Regulamento do Pix e do Manual de Uso da Marca Pix, disponíveis em <a href="https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos" target="_blank" rel="noopener">https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos</a>.</p>
<p><strong>4.4.11.</strong> Os anúncios que Você realizar sobre os instrumentos de pagamento por Você aceitos em transações de pagamento não poderão veicular a marca Pix em dimensão inferior às marcas, aos símbolos ou aos logotipos dos demais instrumento de pagamento aceitos por Você, bem como não poderão indicar ou sugerir que o Pix possua aceitação mais restrita ou menos vantajosa do que os demais instrumentos aceitos por Você, quando tal impressão não corresponda à realidade ou não seja adequadamente justificada por diferenças técnicas.</p>
<p><strong>4.4.12.</strong> O uso da marca Pix, na realização de transações de pagamento, não confere a Você qualquer direito de titularidade ou outro benefício referente àquela marca.</p>
<p><strong>4.4.13.</strong> Caso Você utilize indevidamente a marca Pix, tal utilização implicará em descumprimento destes Termos de Uso, que será comunicado ao Banco Central do Brasil pela Instituição de Pagamento, bem como sujeitará Você às penalidades cabíveis de acordo com a gravidade ou reincidência, quais sejam, (i) suspensão da utilização do Pix como meio de pagamento; (ii) suspensão, bloqueio, limitação de acesso ou cancelamento da Conta, em caso de grave infração, devidamente comprovada (caso em que Você deverá solicitar imediatamente a retirada de eventual saldo disponibilizado em sua Conta); e/ou (iv) responsabilização nas esferas cível, administrativa e criminal na forma prevista na legislação em vigor.</p>
<p><strong>4.4.13.1.</strong> As penalidades acima descritas também poderão ser aplicadas caso Você se recuse ou demore injustificadamente para regularizar o uso da marca Pix, após o recebimento de comunicação da EST Gestão de Bens S/A ou da Instituição de Pagamento.</p>
<p><strong>4.4.14.</strong> Você será notificado caso realize transação suspeita de fraude ou de infração à regulação de prevenção à “lavagem” de dinheiro e ao financiamento do terrorismo, sempre que a Instituição de Pagamento precisar utilizar tempo adicional para análise da transação. Durante o período em que a ordem de pagamento estiver sendo analisada, a Instituição de Pagamento disponibilizará a Você a opção de cancelamento da transação.</p>
<p><strong>4.4.15.</strong> As transações que Você realizar por meio do Pix (pagamentos, recebimentos e devoluções) serão indicadas no extrato da Conta, de forma que essas transações possam ser facilmente diferenciadas de transações que não são do Pix.</p>
<p><strong>5. QUAIS SÃO AS FINALIDADES DO USO DO MEU CARTÃO?</strong></p>
<p><strong>5.1.</strong> Assim que receber o Cartão, Você ficará responsável por conferir os seus dados, sendo certo que o Cartão será entregue bloqueado, por medida de segurança, e que o desbloqueio deverá ser realizado por Você, por meio das Aplicações.</p>
<p><strong>5.2.</strong> Você deverá se atentar ao que prevê o regulamento do arranjo de pagamento aplicável ao Cartão, uma vez que cada arranjo de pagamento é regido por condições e termos específicos.</p>
<p><strong>5.3.</strong> Ao utilizar o Cartão, Você estará automaticamente submetido aos regulamentos específicos da Bandeira, conforme a Lei no 12.865/2013.</p>
<p><strong>5.4.</strong> Você (e seus adicionais, quando indicados e aplicável) poderá contar com o benefício de integrar a plataforma promocional da Visa, acessando descontos, ofertas e promoções disponibilizados pela Visa e seus parceiros. Para tanto, conforme disposto na Política de Privacidade, serão transmitidos à Visa os dados pessoais do Titular e o número do Cartão do Titular.</p>
<p>VOCÊ É O ÚNICO RESPONSÁVEL PELO USO E GUARDA DO SEU CARTÃO FÍSICO. RECOMENDA-SE QUE VOCÊ: (I) GUARDE SEU CARTÃO EM LOCAL SEGURO, JAMAIS PERMITINDO SEU USO POR TERCEIROS; (II) MEMORIZE SUA SENHA E MANTENHA-A EM SIGILO, EVITANDO ANOTAR OU GUARDAR A SENHA EM SUPORTES FÍSICOS OU DIGITAIS, E; (III) NUNCA ANOTE OU GUARDE A SENHA EM CONJUNTO COM SEU CARTÃO.<br />
RECOMENDA-SE AINDA QUE VOCÊ <strong>NÃO</strong> UTILIZE SENHAS RELACIONADAS A DATAS OU OUTRAS REFERÊNCIAS PESSOAIS DO TITULAR, E QUE EFETUE ROTINEIRAMENTE A TROCA DE SUA SENHA COMO MEDIDA DE SEGURANÇA.</p>
<p><strong>5.5.</strong> Se por qualquer razão, Você realizar uma transação que seja autorizada ainda que haja indisponibilidade de saldo suficiente na Conta, Você se compromete a efetuar o pagamento do valor devido pela transação à EST Gestão de Bens S/A no prazo de até 30 dias contados da comunicação do fato pela EST Gestão de Bens S/A.</p>
<p><strong>5.6.</strong> Caso Você não efetue o pagamento neste prazo, a EST Gestão de Bens S/A, independentemente de prévia notificação, e visando o recebimento do valor correspondente à transação efetuada, poderá tomar as medidas que julgar adequadas, tais como, mas não se limitando a (i) bloqueio de transações que impliquem em retirada de valores, (ii) registro de informações do Titular no SERASA, SPC ou qualquer outro serviço similar de proteção ao crédito e/ou (iii) acionamento judicial ou extrajudicial do Titular, respeitados os prazos legais aplicáveis.</p>
<p><strong>5.7.</strong> De toda forma, independentemente de tais medidas, assim que houver saldo suficiente em Conta, a EST Gestão de Bens S/A poderá automaticamente debitar o valor da transação, sem prévia notificação a Você, observado que, restituídos os valores à EST Gestão de Bens S/A, esta reestabelecerá os serviços ou medidas aplicadas a Você em virtude do débito ressarcido.</p>
<p><strong>6. PERDI O CARTÃO. O QUE FAÇO?</strong></p>
<p><strong>6.1.</strong> Em caso de perda, extravio, furto ou roubo do Cartão, Você deve <span style="text-decoration: underline;">imediatamente</span> entrar em contato com qualquer um dos Canais de Comunicação. Após seu contato, o uso e acesso da Conta poderá ser temporariamente bloqueado, até que Você receba novo login e senha. Um novo Cartão será preparado para Você, e será entregue nos prazos informados pelos Canais de Comunicação. Poderão ser cobradas tarifas adicionais para a emissão de um novo Cartão, e, nesta hipótese, tais tarifas serão previamente disponibilizadas a Você.</p>
<p><strong>7. NÃO RECONHEÇO UMA OPERAÇÃO FEITA COM MEU CARTÃO. O QUE FAÇO?</strong></p>
<p><strong>7.1.</strong> Caso Você não reconheça uma operação feita com o seu Cartão, deverá entrar em contato com qualquer um dos Canais de Comunicação no prazo máximo de 90 (noventa) dias corridos, e seguir as orientações para realização do procedimento de Chargeback. O procedimento e a documentação exigida para o Chargeback seguirão as regras estabelecidas pela Bandeira e pela Instituição de Pagamento, de forma que a aprovação do Chargeback só será efetuada quando comprovado o erro ou desacordo comercial e não houver culpa exclusiva do Titular, nos termos das regras supracitadas. Aprovado o Chargeback, o valor será creditado à Conta do Titular, no prazo estabelecido pela Instituição de Pagamento.</p>
<p>VOCÊ ESTÁ CIENTE E DE ACORDO QUE O PROCEDIMENTO DE CHARGEBACK SOMENTE OCORRERÁ PARA TRANSAÇÕES EFETUADAS COM O USO DO CARTÃO. NÃO SERÃO ACEITOS PROCEDIMENTOS DE CHARGEBACK PARA TRANSAÇÕES REALIZADAS POR MEIO DAS APLICAÇÕES E QUE TENHAM SIDO EFETUADAS ATRAVÉS DE LOGIN E SENHA CORRETOS.</p>
<p><strong>8. COMO CANCELO OS SERVIÇOS?</strong></p>
<p><strong>8.1.</strong> Você poderá, a qualquer momento, solicitar o cancelamento de sua Conta e/ou do Cartão, mediante solicitação realizada pelos Canais de Comunicação.</p>
<p><strong>8.2.</strong> Uma vez solicitado o cancelamento da Conta, o Cartão será bloqueado e a Conta será definitivamente encerrada dentro do prazo máximo estabelecido na regulamentação aplicável, sendo facultado a Você, dentro deste prazo: (i) sacar o saldo remanescente; ou (ii) realizar sua transferência para outra conta.</p>
<p><strong>9. EM QUAIS SITUAÇÕES A EST Gestão de Bens S/A E/OU A INSTITUIÇÃO DE PAGAMENTO PODEM CANCELAR MEUS SERVIÇOS?</strong></p>
<p><strong>9.1.</strong> A EST Gestão de Bens S/A ou a Instituição de Pagamento poderão cancelar a prestação dos Serviços imediatamente, comunicando a Você, nas seguintes hipóteses:</p>
<p>(i) caso a Conta fique inativa e sem saldo por mais de 03 meses consecutivos;</p>
<p>(ii) caso Você viole quaisquer das disposições destes Termos de Uso;</p>
<p>(iii) caso sejam verificadas operações fora do padrão de uso, e Você deixe de atender pedido de envio de novos documentos e/ou informações para a comprovação da regularidade dessas operações, nos prazos solicitados;</p>
<p>(iv) em caso de falecimento do Titular.</p>
<p><strong>9.2.</strong> A prestação dos Serviços pode, ainda, ser cancelada imotivadamente e a qualquer momento, mediante comunicação prévia.</p>
<p><strong>9.3.</strong> Exceto em casos de fraudes e/ou por força de lei ou por determinação de autoridade competente, havendo saldo remanescente na Conta, Você deverá indicar conta de mesma titularidade para liberação do valor.</p>
<p><strong>9.4.</strong> A EST Gestão de Bens S/A ou a Instituição de Pagamento poderão, ainda, bloquear parte ou a totalidade do saldo da Conta para atendimento de determinação judicial e/ou de autoridade competente.</p>
<p><strong>10. DE QUEM É A PROPRIEDADE INTELECTUAL SOBRE OS SERVIÇOS?</strong></p>
<p><strong>10.1. </strong>Todos os direitos de propriedade intelectual relativos aos Serviços, bem como todas as suas funcionalidades, são de titularidade exclusiva da EST Gestão de Bens S/A e da Instituição de Pagamento, inclusive no que diz respeito aos seus textos, imagens, layouts, software, códigos, base de dados, gráficos, artigos, fotografias e demais conteúdos produzidos direta ou indiretamente pela Instituição de Pagamento (“Conteúdo”). O Conteúdo é protegido pela lei brasileira de direitos autorais e de propriedade industrial. É proibido usar, copiar, reproduzir, modificar, traduzir, publicar, transmitir, distribuir, executar, fazer o upload, exibir, licenciar, vender explorar ou fazer engenharia reversa do Conteúdo, para qualquer finalidade, sem o consentimento prévio e expresso da EST Gestão de Bens S/A ou da Instituição de Pagamento. Qualquer uso não autorizado do Conteúdo será considerado como violação dos direitos autorais e de propriedade intelectual da Instituição de Pagamento.</p>
<p><strong>10.2. </strong>A EST Gestão de Bens S/A e a Instituição de Pagamento concedem a Você uma licença limitada, temporária, não exclusiva, não transferível e revogável, para usar os Serviços e as Aplicações somente naquilo que seja estritamente necessário para o cumprimento das obrigações e exercício dos direitos previstos nestes Termos de Uso. É proibido ao Titular ceder, sublicenciar, doar, alienar, alugar, transmitir ou transferir os seus direitos e obrigações a terceiros, total ou parcialmente, sob quaisquer modalidades, a qualquer título, bem como é vedado adaptar, descompilar, desmontar ou executar engenharia reversa das Aplicações, de forma que viole os direitos aqui previstos.</p>
<p><strong>10.3.</strong> A EST Gestão de Bens S/A e a Instituição de Pagamento reservam-se o direito de, a seu critério e a qualquer tempo:</p>
<p>(i) alterar ou remover funcionalidades das Aplicações que não estejam alinhadas com seus interesses, bem como adicionar novas que tragam benefícios à utilização das Aplicações, sem qualquer comunicação prévia a Você e sem que lhe seja devida qualquer indenização;</p>
<p>(ii) descontinuar de forma definitiva ou temporária os Serviços disponibilizados por meio da Aplicações, mediante comunicação prévia a Você e sem que lhe seja devida qualquer indenização. Nos casos de descontinuidade definitiva das Aplicações, a EST Gestão de Bens S/A ou a Instituição de Pagamento disponibilizarão os valores que estiverem na Conta;</p>
<p>(iii) suspender e/ou bloquear preventivamente o cadastro e a Conta do Titular, bem como qualquer acesso e uso das Aplicações, pelo período estabelecido na regulamentação aplicável, em caso de mera suspeita de fraude, obtenção de benefício ou vantagem de forma ilícita, ou pelo não cumprimento de quaisquer condições previstas nestes Termos de Uso ou na legislação aplicável. Nesses casos, não será devida qualquer indenização ao Titular, e a EST Gestão de Bens S/A e a Instituição de Pagamento poderão promover a competente ação de regresso, se necessário, bem como tomar quaisquer outras medidas necessárias para perseguir e resguardar seus interesses;</p>
<p><strong>10.4.</strong> Todos os anúncios, ofertas, promoções, marcas, textos e conteúdos de terceiros veiculados através das Aplicações são de propriedade de seus respectivos titulares, sendo expressamente proibida a utilização indevida de quaisquer conteúdos ou marcas apresentadas nas Aplicações.</p>
<p><strong>11. QUAIS SÃO AS LIMITAÇÕES DE RESPONSABILIDADE?</strong></p>
<p><strong>11.1.</strong> A EST Gestão de Bens S/A, A PARCEIRA E A INSTITUIÇÃO DE PAGAMENTO NÃO SÃO RESPONSÁVEIS PELAS PRESTAÇÕES DE SERVIÇOS E ENTREGAS DE PRODUTOS QUE VOCÊ VIER A CONTRATAR DOS ESTABELECIMENTOS A PARTIR DA UTILIZAÇÃO DE SUA CONTA E/OU CARTÃO.</p>
<p><strong>11.2.</strong> É DE RESPONSABILIDADE DO TITULAR: (I) MANTER SEGURO O AMBIENTE DE SEUS DISPOSITIVOS DE ACESSO ÀS APLICAÇÕES, VALENDO-SE DE FERRAMENTAS ESPECÍFICAS PARA TANTO, TAIS COMO ANTIVÍRUS, FIREWALL, ENTRE OUTRAS, DE MODO A CONTRIBUIR PARA A PREVENÇÃO DE RISCOS ELETRÔNICOS; (II) UTILIZAR SISTEMAS OPERACIONAIS ATUALIZADOS E EFICIENTES PARA A PLENA UTILIZAÇÃO DAS APLICAÇÕES; E (III) EQUIPAR-SE E RESPONSABILIZAR-SE PELOS DISPOSITIVOS DE HARDWARE NECESSÁRIOS PARA O ACESSO ÀS APLICAÇÕES, BEM COMO PELO ACESSO DESSES À INTERNET.</p>
<p><strong>11.3.</strong> TODAS AS COMUNICAÇÕES REALIZADAS PELA EMPRESA COM VOCÊ SERÃO FEITAS ATRAVÉS DAS APLICAÇÕES OU DO E-MAIL INDICADO POR VOCÊ NO MOMENTO DO CADASTRO. É SEU DEVER DEIXAR OS SISTEMAS DE ANTI-SPAM CONFIGURADOS DE MODO QUE NÃO INTERFIRAM NO RECEBIMENTO DOS COMUNICADOS. A RESPONSABILIDADE PELO RECEBIMENTO E VISUALIZAÇÃO DOS COMUNICADOS É EXCLUSIVA DO TITULAR.</p>
<p><strong>11.4.</strong> NEM A EST Gestão de Bens S/A, A PARCEIRA OU A INSTITUIÇÃO DE PAGAMENTO SÃO RESPONSÁVEIS PELA VERACIDADE DAS INFORMAÇÕES PESSOAIS OFERECIDAS PELO TITULAR, DE FORMA QUE A RESPONSABILIDADE PELO CONTEÚDO DAS INFORMAÇÕES PESSOAIS É EXCLUSIVA DO TITULAR. O TITULAR ENTENDE QUE A UTILIZAÇÃO DOS SERVIÇOS É VOLTADA APENAS PARA FINS LÍCITOS. A EST Gestão de Bens S/A, A PARCEIRA E/OU A INSTITUIÇÃO DE PAGAMENTO RESERVAM-SE O DIREITO DE IMEDIATAMENTE INTERROMPER O ACESSO À CONTA PELO TITULAR, CASO IDENTIFIQUE A FALSIDADE NO CONTEÚDO DAS INFORMAÇÕES PESSOAIS, BEM COMO A MÁ UTILIZAÇÃO OU USO INADEQUADO DOS SERVIÇOS.</p>
<p><strong>11.5.</strong> TENDO EM VISTA AS CARACTERÍSTICAS INERENTES AO AMBIENTE DA INTERNET, VOCÊ RECONHECE QUE NEM A EST Gestão de Bens S/A, A PARCEIRA OU A INSTITUIÇÃO DE PAGAMENTO SE RESPONSABILIZAM PELAS FALHAS NA PLATAFORMA DECORRENTES DE CIRCUNSTÂNCIAS ALHEIAS À SUA VONTADE E CONTROLE, SEJAM OU NÃO OCASIONADAS POR CASO FORTUITO OU FORÇA MAIOR, COMO POR EXEMPLO, INFORMAÇÕES PERDIDAS, INCOMPLETAS, INVÁLIDAS OU CORROMPIDAS; INTERVENÇÕES DE HACKERS E SOFTWARE MALICIOSOS; FALHAS TÉCNICAS DE QUALQUER TIPO, INCLUINDO, FALHAS NO ACESSO OU NA NAVEGAÇÃO DO SITE DECORRENTES DE FALHAS NA INTERNET EM GERAL, QUEDAS DE ENERGIA, MAU FUNCIONAMENTO ELETRÔNICO E/OU FÍSICO DE QUALQUER REDE, INTERRUPÇÕES OU SUSPENSÕES DE CONEXÃO E FALHAS DE SOFTWARE E/OU HARDWARE DO TITULAR; PARALISAÇÕES PROGRAMADAS PARA MANUTENÇÃO, ATUALIZAÇÃO E AJUSTES DE CONFIGURAÇÃO DAS APLICAÇÕES; QUALQUER FALHA HUMANA DE QUALQUER OUTRO TIPO, QUE POSSA OCORRER DURANTE O PROCESSAMENTO DAS INFORMAÇÕES, EXIMINDO-SE DE QUALQUER RESPONSABILIDADE PROVENIENTE DE TAIS FATOS E/OU ATOS.</p>
<p><strong>12. COMO ENTRO EM CONTATO PARA DÚVIDAS E SOLICITAÇÕES?</strong></p>
<p><strong>12.1.</strong> Qualquer dúvida ou solicitação deverá ser sempre encaminhada aos Canais de Comunicação. Qualquer outra forma de comunicação com a EST Gestão de Bens S/A, a Parceira ou com a Instituição de Pagamento que seja realizada fora dos Canais de Comunicação não será reconhecida.</p>
<p>VOCÊ OBRIGA-SE A INFORMAR IMEDIATAMENTE QUAISQUER MUDANÇAS DE NÚMERO DE TELEFONE, ENDEREÇO E ENDEREÇO DE E-MAIL, A FIM DE QUE POSSA RECEBER REGULARMENTE COMUNICAÇÕES IMPORTANTES DOS CANAIS DE COMUNICAÇÃO.</p>
<p><strong>13. O QUE MAIS PRECISO SABER?</strong></p>
<p><strong>13.1. Benefícios e Serviços:</strong> A Instituição de Pagamento não será responsável por qualquer oferta de benefícios, serviços, estratégias de marketing e propagandas publicitárias, tais como campanhas de cashback, premiações e correlatos, disponibilizados exclusivamente e diretamente pela EST Gestão de Bens S/A.</p>
<p><strong>13.2. Atualizações.</strong> A Instituição de Pagamento e a EST Gestão de Bens S/A estão sempre fazendo atualizações nas Aplicações, por esse motivo, durante a vigência destes Termos de Uso, a Instituição de Pagamento e a EST Gestão de Bens S/A poderão atualizar as Aplicações com o objetivo de preservar ou aperfeiçoar suas características funcionais. Nesse caso, suspensões temporárias nos Serviços poderão acontecer e Você deverá baixar as versões atualizadas das Aplicações, caso queira fazer uso dessas atualizações.</p>
<p><strong>13.2.1.</strong> Os Termos de Uso poderão ser alterados, a qualquer tempo, a fim de refletir os ajustes realizados nas Aplicações quando necessário e aplicável. No entanto, sempre que ocorrer qualquer modificação nestes Termos de Uso, Você será informado por meio de uma nota em destaque dentro das Aplicações. Caso Você não concorde com os novos Termos de Uso, poderá rejeitá-los, mas, infelizmente, isso significa que Você não poderá mais fazer uso das Aplicações. Se de qualquer maneira Você utilizar as Aplicações mesmo após a alteração destes Termos de Uso, isso significa que Você concorda com todas as modificações.</p>
<p><strong>13.3. Aplicativos de Terceiros.</strong> Atualmente, uma série de soluções de hardware e software oferecem a possibilidade de integração com outras aplicações (“Aplicações de Terceiros”), sendo que alguns desses Aplicativos de Terceiros poderão ter sua integração com as Aplicações disponibilizadas pelo Parceiro. O uso dessas Aplicações de Terceiros é de única e exclusiva responsabilidade do Titular, que se obriga, ainda, a não integrar as Aplicações, sua Conta ou seu Cartão a quaisquer outras Aplicações de Terceiros que não sejam autorizadas pela EST Gestão de Bens S/A, pela Parceira ou pela Instituição de Pagamento. As Aplicações de Terceiros poderão ter seus próprios termos e condições de uso e políticas de privacidade e, então, também serão regidas pelos respectivos termos e condições, e às respectivas políticas de privacidade.</p>
<p><strong>13.3.1.</strong> VOCÊ COMPREENDE E CONCORDA QUE A EMPRESA, A PARCEIRA E A INSTITUIÇÃO DE PAGAMENTO NÃO ENDOSSAM E NÃO SÃO RESPONSÁVEIS PELO COMPORTAMENTO, RECURSOS OU CONTEÚDO DE QUAISQUER APLICAÇÕES DE TERCEIRO, OU POR QUALQUER TRANSAÇÃO QUE VOCÊ POSSA FAZER COM O PROVEDOR DE TAIS APLICAÇÕES DE TERCEIROS.</p>
<p><strong>13.4. Comunicação ao Banco Central do Brasil.</strong> Você desde já concorda que a EST Gestão de Bens S/A, a Parceira, a Instituição de Pagamento e a Instituição Financeira comunicarão ao Banco Central do Brasil, ao Conselho de Controle de Atividades Financeiras ou outros órgãos que a legislação previr, as operações que possam estar configuradas na Lei 9.613/98 (que dispõe sobre os crimes de lavagem ou ocultação de bens, direitos e valores) e demais disposições legais pertinentes à matéria.</p>
<p><strong>13.5. Cessão.</strong> A EST Gestão de Bens S/A e a Instituição de Pagamento poderão, a qualquer momento, ceder quaisquer de seus direitos e obrigações previstos nestes Termos de Uso a qualquer pessoa, física ou jurídica, mediante simples notificação prévia a Você, ficando desde já ressalvado que a cessionária continuará a cumprir com todas as obrigações assumidas pela EST Gestão de Bens S/A e/ou Instituição de Pagamento.</p>
<p><strong>13.6. Lei Aplicável.</strong> Estes Termos de Uso são regidos pelas leis da República Federativa do Brasil. Quaisquer dúvidas e situações não previstas nestes Termos de Uso serão primeiramente resolvidas pela EST Gestão de Bens S/A e, caso persistam, deverão ser solucionadas pelos órgãos do sistema brasileiro de defesa do consumidor.</p>
            </div>
        </div>
    </div>
</section>

@endsection