@extends ('menu')

@section ('title', 'Termo e Condições de Uso do Totem ou POS : EstBank' )

@section ('conteudo')
<div class="container"></div>

<section class="section-scroll section-one">
    <div class="container">
        <div class="row">
            <div class="col-12 px-3">
                <h3 class="bradcrumb c-gray-blue mt-5 pt-4"></h3>
                <div class="d-flex align-items-center justify-content-center">
                    <h1 class="subtitle-small c-pink mb-0 text-uppercase">Termo e Condições de Uso do Totem ou POS</h1>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12 col-sm-10 offset-sm-1 px-5 c-gray-blue text-scroll-small">
                <p>Estes Termos e Condições Gerais constituem um contrato celebrado entre a EST Gestão de Bens S/A, inscrita no CNPJ/MF no 37.920.778/0001-29, sediada à Av. Nove de Julho, 3147, 11o andar, Jardim Paulista, São Paulo – SP, CEP: 01.407-000, disponível em www.estbank.com.br (adiante denominado &#8220;ESTBANK&#8221;) e qualquer pessoa que atenda todos os requisitos destes Termos e Condições Gerais (adiante denominada &#8220;Usuário&#8221; ou no plural &#8220;Usuários&#8221;) e que deseje contratar os serviços oferecidos pela ESTBANK.</p>
<p>A ESTBANK é uma empresa que atua em atividades Auxiliares dos Serviços Financeiros; Casas de Cambio; Clube de Benefícios e Assistências Complementares; Corretagem de Consórcios e Seguros; Serviços de Intermediação na Obtenção de Empréstimos; Comercialização de Quotas de Consórcio; Serviços de Locação de Terminais Eletrônicos; Maquininhas de Cartão de Débito Crédito; Títulos de Capitalização; Emissão de Vales Alimentação, Transporte e Similares; Atividades de Intermediação, Agenciamento de Serviços e Negócios em Geral, exceto Imobiliários; Atividades de Cobranças e Informações Cadastrais, Desenvolvimento e Licenciamento de Programas de Computador Customizáveis; Consultoria em Tecnologia da Informação; Administração de Cartões de Credito; Portais, Provedores de Conteúdo e outros Serviços de Informação na Internet; Tratamento de Dados e Serviços de Hospedagem na Internet. Detém plataforma de tecnologia de serviços de pagamento por meio de Totem de Atendimento e Maquininhas, através do qual as transações de pagamento realizadas pelos compradores são processadas e liquidadas para os vendedores, conforme regras e procedimentos determinados nestes Termos e Condições.</p>
<p>A ESTBANK não realiza a prestação de serviços privativos de instituição financeira.</p>
<p>A aceitação destes termos e condições gerais é absolutamente indispensável à utilização dos serviços prestados pela ESTBANK.</p>
<p>Nestes Termos e Condições Gerais são descritos os direitos e responsabilidades dos Usuários e da ESTBANK ao utilizar os Serviços de Pagamento.</p>
<p>O Usuário deve ler, entender e aceitar todas as condições estabelecidas nestes Termos e Condições Gerais e demais políticas incorporadas por referência antes de cadastrar-se como Usuário da plataforma do TOTEM DE ATENDIMENTO ou da Maquininha da ESTBANK.</p>
<p><u>Ao se cadastrar como usuário o cliente poderá utilizar todos os serviços disponibilizados por meio do TOTEM DE ATENDIMENTO e/ou da Maquininha, declarando para tanto ter lido, compreendido e aceitado os respectivos Termos e Condições de Uso de cada serviço, os quais fazem parte integrante destes Termos e Condições Gerais.</u></p>
<p><strong>DEFINIÇÕES</strong></p>
<p><strong>MAQUININHAS:</strong> são as maquinas de cartão de crédito e débito que fazem leitura e<br />
pagamento de boletos.</p>
<p><strong>TOTEM DE AUTO ATENDIMENTO:</strong> Equipamento onde o Usuário poderá realizar o pagamento de boletos.</p>
<p><strong>USUÁRIO:</strong> Pessoa Física ou Jurídica que, cadastrando-se no Totem de Auto Atendimento ou na Maquininha, realizará o pagamento de boletos e/ou transações.</p>
<p><strong>RECEBEDOR:</strong> É a pessoa física ou jurídica que credora do usuário, que receberá o valor descrito no boleto ou transação que será realizada.</p>
<p><strong>1- PRESTAÇÃO DE SERVIÇOS DE PAGAMENTO</strong></p>
<p><strong>1.1.</strong> O Usuário poderá utilizar os Serviços de Pagamento disponibilizados pela Plataforma Estbank – por meio da Maquininha ou do TOTEM DE AUTO ATENDIMENTO – para o pagamento de contas de concessionárias de serviços públicos, tributos com código de barras e boletos bancários (denominados, simplesmente, “Títulos”).</p>
<p><strong>1.2.</strong> A transação a ser realizada pelo Usuário na Plataforma ESTBANK deverá detalhar as instruções e informações referentes ao título a ser pago. O Usuário assume inteira responsabilidade pelas instruções e informações que detalhar, eximindo a ESTBANK de quaisquer responsabilidades neste sentido, inclusive quanto à idoneidade e veracidade dos títulos a serem pagos.</p>
<p><strong>1.3.</strong> Para que o pagamento do título seja realizado no mesmo dia da Transação, as Transações deverão ser formalizadas pelo Usuário até às 18h (dezoito horas), ficando desde já esclarecido que a ESTBANK somente prestará os Serviços de Pagamento se forem observadas as datas de vencimento previstas nos títulos. Não obstante, o Usuário desde já assume inteira responsabilidade pelo pagamento de um título eventualmente realizado pela ESTBANK mediante uma Transação realizada pelo Usuário após o respectivo prazo de vencimento, caso haja o estorno do referido pagamento, eximindo a ESTBANK de quaisquer responsabilidades neste sentido.</p>
<p><strong>1.4.</strong> As Transações para pagamento de Títulos realizadas pelo Usuário em finais de semana (sábados e domingos) e dias não úteis, serão consideradas como efetuadas no primeiro dia útil imediatamente seguinte.</p>
<p><strong>1.5.</strong> No caso de o Usuário optar pelo pagamento por meio de cartão de crédito, a Transação somente será realizada pela ESTBANK se a operação for devidamente autorizada pelo emissor do cartão.</p>
<p><strong>1.6.</strong> Uma vez realizado o pagamento, o Usuário poderá imprimir o respectivo comprovante de pagamento no TOTEM DE AUTO ATENDIMENTO e/ou na Maquininha.</p>
<p><strong>1.7.</strong> Na ocorrência de qualquer divergência a menor apurada no pagamento, o Usuário que tenha conta ESTBANK, desde já autoriza a ESTBANK proceder o desconto da diferença sobre o saldo eventualmente existente em sua Conta. Na inexistência de saldo, o Usuário que tenha conta ESTBANK, desde já se compromete a aportar os recursos necessários em sua Conta para liquidar esta diferença.</p>
<p><strong>1.8.</strong> Em caso de pagamento a maior ou em duplicidade, o Usuário deverá entrar em contato com o cedente do título a fim de solicitar o ressarcimento do valor devido.</p>
<p><strong>1.9.</strong> A ESTBANK reserva-se o direito de determinar o montante máximo de pagamentos de Títulos que podem ser realizados sem custos adicionais. Eventuais custos adicionais serão informados no momento da Transação excedente.</p>
<p><strong>1.10.</strong> O Usuário declara estar ciente de que os Serviços de Pagamento de Títulos ora tratados envolvem a utilização de serviços financeiros prestados por determinada instituição financeira à ESTBANK. Neste sentido, o Usuário, desde já, exime a ESTBANK de quaisquer prejuízos que venham a ser causados e/ou responsabilidades que possam advir decorrentes de problemas verificados nos sistemas operacionais e tecnológicos da referida instituição financeira.</p>
<p><strong>1.11.</strong> A ESTBANK reserva-se o direito de não processar as Transações que: (i) contenham dados incompletos, contraditórios ou inválidos; (ii) a ESTBANK, a seu exclusivo critério, considere envolver algum risco; (ii) estejam em desacordo aos presentes Termos e Condições; ou (iv) não sejam autorizadas pelo banco ou pela credenciadora ou pelo emissor de cartões de crédito ou débito.</p>
<p><strong>1.12.</strong> A ESTBANK não será responsável por ordens, instruções e/ou Transações equivocadas ou incompletas causadas por: (i) introdução errônea do e-mail; (ii) informação errônea ou incompleta do Recebedor, da operação de pagamento e/ou quaisquer outros dados fornecidos pelo Usuário Pagador; e/ou (iii) objeto ilícito ou em desacordo com os Termos e Condições.</p>
<p><strong>1.13.</strong> É de responsabilidade exclusiva do Usuário o pagamento, recolhimento e/ou retenção de tributos federais, estaduais e municipais devidos em razão de qualquer Transação. O Usuário reconhece que a ESTBANK não possui qualquer relação com o objeto das Transações, devendo mantê-la indene de quaisquer obrigações, especialmente as de ordem tributária e fiscal.</p>
<p><strong>1.14.</strong> O Usuário reconhece e concorda que em nenhuma hipótese, poderá atrelar os serviços de pagamento oferecidos pela ESTBANK a uma oferta falsa ou enganosa de produto ou serviço.</p>
<p><strong>1.15.</strong> Se o Usuário realizar o pagamento de boleto de forma parcelada, por meio de cartão de crédito, deverá observar a incidência de juros nas parcelas e só aceitar o parcelamento se estiver de acordo com os juros incidentes.</p>
<p><strong>1.16.</strong> O Usuário poderá realizar o parcelamento de boleto (s) por meio de até 4 (quatro) cartões de crédito, sendo necessário introduzir a senha de segurança do titular do cartão. Se o parcelamento for realizado em cartão de crédito de titularidade diversa do Usuário, entende-se que houve a anuência do titular para que fosse efetuado tal débito, uma vez que este tem o dever de zelar pela senha de segurança, isentando assim a ESTBANK de qualquer responsabilidade cível ou criminal.</p>
<p><strong>2- AUTORIZAÇÃO PARA CONSULTA AO SCR E BANCOS DE DADOS</strong></p>
<p><strong>2.1.</strong> Por meio da presente cláusula, o Usuário está ciente e concorda que a(s) empresa(s) parceira(s) da ESTBANK, poderá(ão) consultar os débitos e responsabilidades decorrentes de operações com características de crédito, as informações e os registros de medidas judiciais que em seu nome e/ou razão social, conforme o caso, que constem ou venham a constar do Sistema de Informações de Crédito (“SCR”), gerido pelo Banco Central do Brasil (“BACEN”) ou dos sistemas que venham a complementá-lo ou a substituí-lo, pois essa consulta é essencial para a análise de ofertas e concessão de produtos financeiros e empréstimos, bem como fornecer ao BACEN, para integrar o SCR, informações sobre as operações contratadas, incluindo o montante de suas dívidas a vencer e vencidas, as em atraso e/ou as operações baixadas com prejuízo.</p>
<p><strong>2.2.</strong> O Usuário fica desde já ciente de que: (a) o SCR tem por finalidades fornecer informações ao BACEN para fins de supervisão do risco de crédito a que estão expostas as instituições financeiras e propiciar o intercâmbio de informações entre essas instituições com o objetivo de subsidiar decisões de crédito e de negócios; (b) o SCR é alimentado mensalmente pelas instituições financeiras, mediante coleta de informações sobre operações concedidas com responsabilidade igual ou superior a R$ 200,00 (duzentos reais), vencidas e vincendas, bem como valores referentes às fianças e avais prestados pelas instituições financeiras a seus clientes e as informações remetidas ao SCR são de exclusiva responsabilidade da instituição financeira remetente, inclusive no que tange às inclusões, correções, exclusões, registro de medidas judiciais e manifestações de discordância quanto às tais informações constantes no sistema, sendo certo que somente a instituição financeira responsável pela inclusão poderá alterá-la ou excluí-la; (c) as instituições financeiras são obrigadas por regulamentação do BACEN a enviar ao SCR informações do Usuário referentes às operações de crédito por ele contratadas, e que o Usuário poderá ter acesso aos dados constantes neste Sistema por meio do Registro – Extrato de Registro de Informações no Banco Central, um sistema que fornece gratuitamente informações disponíveis em cadastros administrados pelo BACEN; (d) correções, exclusões e manifestações de discordância quanto às informações constantes no SCR deverão ser dirigidas à instituição financeira; e (e) mais informações sobre o SCR podem também ser obtidas em consulta ao ambiente virtual do Banco Central do Brasil (<a href="http://www.bcb.gov.br/" target="_blank" rel="noopener">www.bcb.gov.br</a>).</p>
<p><strong>2.3.</strong> A ESTBANK e/ou empresas parceiras, poderá(ão) (a) acessar dados e informações financeiras relativas ao Usuário junto a serviços de proteção de crédito, incluindo a SERASA – Centralização de Serviços dos Bancos S.A e quaisquer outros órgãos, bancos de dados, entidades ou empresas que julgar pertinentes; (b) trocar e incluir informações cadastrais, financeiras e de crédito a respeito do Usuário nesses bancos de dados e junto a instituições financeiras; e (c) providenciar a abertura de cadastro visando à formação de histórico de crédito do Usuário.</p>
<p><strong>2.4.</strong> Caso a ESTBANK verifique qualquer divergência, inexatidão ou irregularidade dos dados de cadastro do Usuário, poderá solicitar ao mesmo que atualize e/ou regularize sua situação cadastral e, caso tal solicitação não seja atendida no prazo concedido, o Usuário poderá ter sua Transação negada, ser suspenso ou inabilitado da Plataforma ESTBANK.</p>
<p><strong>3- CANCELAMENTO E <em>CHARGEBACK</em> (contestação de débito)</strong></p>
<p><strong>3.1. Cancelamento.</strong> A ESTBANK poderá cancelar uma Transação sempre que verificar que a mesma: (i) foi invalidada pelo banco do Usuário Pagador; (ii) foi processada incorretamente pela ESTBANK, (iii) o Usuário Pagador não tinha autorização para enviá- lo, seja por fraude ou qualquer outro motivo, (iv) decorre de Operações Proibidas ou de qualquer operação em desacordo com estes Termos e Condições, ou (v) caso de suspeita de fraude ou qualquer irregularidade.</p>
<p><strong>3.2. Chargeback.</strong> Caso o Usuário Pagador tenha realizado o <em>Chargeback</em> sobre os valores envolvidos na Transação após o envio, esses valores serão descontados e debitados da Conta do Recebedor, salvo se o Recebedor estiver coberto pelo Programa de Proteção ao Vendedor ou da Conta do Usuário Pagador nos casos em que o <em>Chargeback</em> for indevido, ou em qualquer outra Conta de mesma titularidade do Usuário responsável pelo <em>Chargeback</em> ou em nome de terceiros, em que há suspeita de que a finalidade de tal nova Conta seja a de fraudar credores e/ou burlar os presentes Termos e Condições. Em virtude disso, o Usuário autoriza expressamente a ESTBANK reter de sua Conta o saldo em Moeda Eletrônica necessário para cobrir o cancelamento, a reversão ou <em>Chargeback</em>, quando aplicável. Se o Usuário não dispuser de saldo suficiente em sua Conta, a ESTBANK está autorizado a reter tais valores de qualquer outro ingresso futuro de dinheiro em sua Conta, até que o valor devido em razão do cancelamento, reversão ou <em>Chargeback</em> seja compensado.</p>
<p><strong>3.3.</strong> Caso o Usuário não realize o pagamento correspondente ao <em>Chargeback</em>, cancelamento ou reversão, a ESTBANK poderá: (i) aplicar multa correspondente a 2% (dois por cento) do valor devido, além dos juros de mora de 1% (um por cento) ao mês; (ii) encaminhar o débito do Usuário para agências de cobrança externas para negociação e/ou cobrança judicial ou extrajudicial; e (iv) comunicar a inadimplência do Usuário a órgãos e entidades de proteção ao crédito.</p>
<p><strong>3.4.</strong> O Usuário deverá, quando solicitado pela ESTBANK, fornecer documentação referente à Transação objeto do <em>Chargeback</em>, cancelamento ou reversão no prazo máximo de 10 (dez) dias corridos contados do envio da solicitação pela ESTBANK.</p>
<p><strong>3.5.</strong> Para contestar o <em>Chargeback</em>, cancelamento ou reversão, o Usuário deverá reunir provas que endossem e confirmem seu relato. O fornecimento de tais documentos não implicará que o dinheiro do Usuário seja novamente creditado em sua Conta.</p>
<p><strong>3.6.</strong> Caso seja constatado que o Chargeback foi indevido, o Usuário Pagador ficará obrigado ao pagamento da Transação correspondente à ESTBANK e/ou a terceiros, sob pena da adoção, pela ESTBANK, das medidas judiciais ou extrajudiciais que entenda pertinentes para reaver os valores envolvidos na Transação objeto do <em>Chargeback</em> indevido, inclusive podendo comunicar esta inadimplência do Usuário Pagador a órgãos e entidades de proteção ao crédito.</p>
<p><strong>3.7.</strong> Caso haja uma reversão, cancelamento ou <em>Chargeback</em>, o Recebedor poderá responder perante a ESTBANK pelo valor envolvido na Transação, acrescido de quaisquer outros custos ou gastos relacionados. A ESTBANK poderá iniciar as medidas judiciais ou extrajudiciais que entenda pertinentes para reaver os valores envolvidos na Transação objeto do <em>Chargeback</em>, que não seja ressarcida pelo Recebedor dentro do prazo aqui estabelecido.</p>
<p><strong>3.8.</strong> Caso identifique níveis excessivos de <em>chargeback</em> de seus Usuários, seja Pagador, seja Recebedor, a ESTBANK poderá, dentre outras medidas: (i) bloquear total ou parcialmente os valores existentes na Conta do Usuário, como garantia para cobrir potenciais danos à ESTBANK, incluindo, mas não se limitando a eventuais multas aplicadas pelas bandeiras e credenciadoras de cartão; e (ii) suspender ou inabilitar permanentemente o Usuário.</p>
<p><strong>3.9.</strong> Os valores eventualmente bloqueados em decorrência do excesso de <em>chargebacks</em> poderão ser usados a título de compensação pela ESTBANK para o ressarcimento de eventuais custos, despesas ou danos que lhe foram causados.</p>
<p><strong>4 &#8211; OBRIGAÇÕES DA ESTBANK</strong></p>
<p><strong>4.1.</strong> A ESTBANK se obriga a seguir as instruções recebidas do Usuário para efetivar as<br />
Transações/Pagamentos.</p>
<p><strong>4.2.</strong> A ESTBANK envidará os melhores esforços para assegurar o cumprimento dos prazos indicados nestes Termos e Condições. Não obstante, o Usuário está ciente que, por determinados fatores externos que fujam ao controle da ESTBANK, poderão ocorrer atrasos, motivo pelo qual o Usuário exime a ESTBANK de toda e qualquer responsabilidade decorrente de eventuais inconvenientes ou prejuízos.</p>
<p><strong>4.3.</strong> O Usuário reconhece estar sujeito aos riscos da instabilidade da rede mundial de computadores, sendo que a ESTBANK não poderá ser responsabilizada por eventuais falhas na prestação dos serviços decorrentes de interrupções ou atrasos em virtude de<br />
falhas na rede mundial de computadores que possam impedir ou prejudicar o envio e recebimento de informações.</p>
<p><strong>4.4.</strong> A ESTBANK não será responsável por eventual Transação que não seja efetivada em decorrência da intervenção pelo Banco Central ou da insolvência de qualquer Banco, Instituição Financeira.</p>
<p><strong>4.5.</strong> A ESTBANK também não poderá ser responsabilizada por ordens de pagamento não processadas ou recusadas, contas bancárias de terceiros suspensas ou canceladas.</p>
<p><strong>5- CONDIÇÕES GERAIS</strong></p>
<p><strong>5.1. Declarações do Usuário:</strong> Sem prejuízo das demais disposições destes Termos e Condições, o Usuário declara e garante que as Transações por ele realizadas na Plataforma ESTBANK não serão utilizadas para, mas sem limitação a: (i) Infração a legislação em vigor; (ii) Exploração de jogos de azar, apostas, etc.; (iv) Cobranças e pagamentos de condomínios prediais; (v) Atividades de organizações sindicais; (vi) Atividades de organizações políticas, salvo as autorizadas por lei; (vii) Exploração de máquinas de serviços pessoais acionadas por moeda; (viii) Oferecimento de cartões de descontos; (ix) Serviços de recolocação profissional; (x) Tráfico de armas, de pessoas, de animais, etc.; (xi) Lavagem de dinheiro; (xii) Terrorismo; (xiii) Pornografia, prostituição ou pedofilia; e/ou (xiv) Qualquer tipo de atividade que possa ser considerada fraudulenta ou ilegal.</p>
<p><strong>5.2.</strong> O Usuário não utilizará a Plataforma ESTBANK para efetuar qualquer operação que se possa considerar ou interpretar como adiantamento de dinheiro, autofinanciamento, lavagem de dinheiro, empréstimo ou outras formas semelhantes como definido em Lei, bem como toda e qualquer atividade que não esteja em consonância com a legislação brasileira.</p>
<p><strong>5.3.</strong> Caso a ESTBANK considere, a seu exclusivo critério, que há suspeita ou indício da utilização indevida do Plataforma ESTBANK para alguma atividade proibida pela lei ou contrária ao disposto nos presentes Termos e Condições, ou suspeite de comportamentos fraudulentos ou que atentem contra a imagem da ESTBANK, seus acionistas, controladores, controladas, filiais ou subsidiárias, funcionários, empregados, diretores, agentes, Usuários e/ou terceiros, a ESTBANK poderá, sem notificação prévia, recusar, cancelar ou suspender uma Transação, sem prejuízo de que sejam eventualmente adotadas as medidas judiciais ou extrajudiciais pertinentes.</p>
<p><strong>5.4.</strong> A ESTBANK não é instituição financeira, tampouco seguradora: As Partes reconhecem que a presente contratação ou qualquer condição presente nestes Termos e Condições não implica na caracterização da ESTBANK como uma instituição financeira, tampouco seguradora. A ESTBANK não presta nenhum serviço bancário ou de câmbio ao Usuário, e tampouco qualquer outra atividade privativa de instituições financeiras ou seguradoras, ou quaisquer outras que sejam reguladas ou fiscalizadas pelo Banco Central, Comissão de Valores Mobiliários (CVM) ou pela Superintendência de Seguros<br />
Privados (Susep), para as quais a ESTBANK não detenha autorização e/ou esteja em processo de autorização perante a autoridade competente. As Partes reconhecem que a ESTBANK apenas oferece um Serviço de Pagamento por conta e ordem dos Usuários de acordo com as condições estabelecidas nestes Termos e Condições.</p>
<p><strong>5.5.</strong> Processamento de pagamento: O Usuário declara e reconhece que o processamento de pagamentos pela ESTBANK depende do cumprimento de alguns procedimentos, como análise de risco e compensação bancária, a depender do meio utilizado. Em regra, os pagamentos por cartão de crédito ou saldo em Conta são processados de forma mais rápida do que pagamentos realizados por boleto bancário. Neste sentido, a ESTBANK não poderá ser responsável por eventuais descumprimentos de oferta feita pelo Recebedor quando o processamento de pagamento ocorrer depois de esgotado o estoque do produto anunciado.</p>
<p><strong>5.6. Privacidade da Informação:</strong> Toda informação ou dado pessoal do Usuário é armazenado em servidores ou meios magnéticos de alta segurança. A ESTBANK adotará todas as medidas possíveis para manter a confidencialidade e a segurança das informações sigilosas, porém não se responsabilizará por eventuais prejuízos que sejam decorrentes da divulgação de tais informações por parte de terceiros que utilizem as redes públicas ou a internet, subvertendo os sistemas de segurança para acessar as informações de Usuários.</p>
<p>O Usuário expressamente autoriza que suas informações e dados pessoais sejam compartilhados pela ESTBANK com as demais empresas integrantes do grupo econômico, parceiros comerciais, autoridades e pessoas físicas ou jurídicas que aleguem ter sido lesadas por Usuários.</p>
<p><strong>5.7. Responsabilidade exclusiva do Usuário por suas próprias operações:</strong> Em virtude da ESTBANK não figurar como parte nas negociações de compra e venda de serviços e produtos que se realizam entre os Usuários Pagador e Recebedor, a responsabilidade por todas as obrigações decorrentes da compra e venda, sejam fiscais, trabalhistas, consumeristas ou de qualquer outra natureza, será exclusivamente do Recebedor.</p>
<p><strong>5.8.</strong> UMA VEZ QUE A ESTBANK NÃO POSSUI QUALQUER RELAÇÃO COM A OBRIGAÇÃO QUE DEU ORIGEM À TRANSAÇÃO, A ESTBANK NÃO SERÁ RESPONSÁVEL, TAMPOUCO VERIFICARÁ AS CAUSAS, PREÇO OU QUALQUER OUTRA CIRCUNSTÂNCIA RELATIVA A TAL TRANSAÇÃO, ASSIM COMO EM RESPEITO À EXISTÊNCIA, QUALIDADE, QUANTIDADE, FUNCIONAMENTO, ESTADO, INTEGRIDADE OU LEGITIMIDADE DOS BENS OU SERVIÇOS OFERECIDOS, ADQUIRIDOS OU ALIENADOS PELOS USUÁRIOS E PAGOS UTILIZANDO A PLATAFORMA ESTBANK, ASSIM COMO DA CAPACIDADE PARA CONTRATAR DOS USUÁRIOS E A VERACIDADE DOS DADOS PESSOAIS POR ELES INSERIDOS.</p>
<p><strong>5.9. Licença limitada:</strong> Todos os direitos de Propriedade Intelectual sobre a Plataforma, as Ferramentas de Pagamentos e seus códigos, o desenvolvimento, os programas de computador, equipamentos, domínios, logomarcas, logotipos, desenhos, estrutura, conteúdos, informação, etc., são de propriedade da ESTBANK e/ou suas sociedades controladoras, controladas, filiais ou subsidiárias. Em nenhum caso se entenderá que o<br />
Usuário tem algum tipo de direito sobre os mesmos, independentemente dos direitos conferidos sobre o uso das ferramentas que a ESTBANK coloca à disposição do Usuário. A ESTBANK somente autoriza o Usuário a fazer uso de seus direitos de Propriedade Intelectual, no que refere às Ferramentas de Pagamentos colocadas à disposição do Usuário para o cumprimento das atividades derivadas dos presentes Termos e Condições em seu site eletrônico, fazendo relação direta aos Serviços de Pagamento da ESTBANK. Qualquer outra utilização de tais direitos de Propriedade Intelectual da ESTBANK é estritamente proibida, inclusive no que tange à engenharia reversa envolvendo os softwares disponibilizados. Observadas tais limitações, a ESTBANK outorga ao Usuário uma licença gratuita, não exclusiva e revogável a qualquer tempo para utilização das Ferramentas de Pagamento nos termos do disposto nos presentes Termos e Condições.</p>
<p><strong>5.10. Modificações dos Termos e Condições:</strong> A ESTBANK poderá modificar a qualquer momento, sem aviso prévio, estes Termos e Condições. A ESTBANK notificará as mudanças ao Usuário publicando uma versão atualizada destes Termos e Condições na Plataforma ESTBANK, explicitando a data da última modificação e por meio de comunicação enviada ao endereço de e-mail principal do Usuário (que optar pelo recebimento deste tipo de comunicação por e-mail no ato de sua adesão a estes Termos e Condições).</p>
<p><strong>5.11. Registro das operações:</strong> O Usuário autoriza de forma irrevogável a ESTBANK ou quem a ESTBANK designe, a gravar todas as operações e/ou telefonemas do Usuário relativos aos serviços prestados pela ESTBANK, e a utilizar essas gravações como meio probatório perante autoridades administrativas ou judiciais. Os registros emitidos pela ESTBANK serão considerados prova suficiente do cumprimento das Transações, substituem a necessidade de qualquer recibo e são plenamente oponíveis ao Usuário.</p>
<p><strong>5.12. Notificações:</strong> Serão válidas todas as notificações realizadas aos Usuários pela ESTBANK no endereço físico ou de correio eletrônico principal cadastrado por estes, por mensagem de texto enviada para o número de celular cadastrado, (SMS ou whatsapp).</p>
<p><strong>5.13. Solução de controvérsias e direito de arrependimento:</strong> Na ocorrência de eventual conflito, o Usuário pode buscar uma solução amigável fazendo uma Reclamação por meio do Portal de Contato disponível em www.estbank.com.br</p>
<p><strong>5.14. Canais de Atendimento:</strong> o Usuário poderá entrar em contato com a ESTBANK pelos seguintes canais:</p>
<p>SAC (Serviço de Atendimento ao Consumidor) &#8211; para informações, dúvidas ou problemas sobre os produtos ou serviços da ESTBANK, disponível das 09h às 18h de segunda a sexta:</p>
<p>Telefone: 0800 942 7594</p>
<p>Site: www.estbank.com.br</p>
<p><strong>5.15. Jurisdição e lei aplicável:</strong> Todos os itens destes Termos e Condições são regidos pelas leis vigentes na República Federativa do Brasil. Para todos os assuntos referentes à interpretação, ao cumprimento ou qualquer outro questionamento relacionado a estes Termos e Condições, as Partes concordam em se submeter ao Foro da Comarca de São Paulo/SP, com exceção de reclamações apresentadas por Usuários que se enquadrem no conceito legal de consumidores, que poderão submeter tais reclamações ao foro de seu domicílio.</p>
<p><strong>5.16. Endereço para envio de correspondências:</strong> Todas as requisições, correspondências, notificações ou pedidos de informação deverão ser enviadas para o endereço da ESTBANK, na Avenida Nove de Julho, no 3.147, 11° andar, Jd. Paulista São Paulo/SP &#8211; CEP 06233-903.</p>
            </div>
        </div>
    </div>
</section>




@endsection